### ISSUE TITLE
Set up for geofence monitoring (permissions)

### ISSUE THREAD

**Issue by Swando97** [Swando97/GeoFriendv0.2#2]
Create geofence object setting the desired radius, duration, and transition types for the geofence.

**Comment by EdwardYeung6** [comment]
![Screenshot (184)](https://user-images.githubusercontent.com/57809982/99202611-9aaa5880-2764-11eb-8c2b-39569fba81cf.png)
![Screenshot (185)](https://user-images.githubusercontent.com/57809982/99202616-9b42ef00-2764-11eb-9a80-759a18bd43f3.png)
![Screenshot (186)](https://user-images.githubusercontent.com/57809982/99202617-9bdb8580-2764-11eb-8702-7c64c5d3a918.png)
![Screenshot (187)](https://user-images.githubusercontent.com/57809982/99202618-9bdb8580-2764-11eb-8514-feab15b5ac9b.png)
![Screenshot (188)](https://user-images.githubusercontent.com/57809982/99202619-9c741c00-2764-11eb-9813-b8a0bc585379.png)
![Screenshot (189)](https://user-images.githubusercontent.com/57809982/99202620-9c741c00-2764-11eb-8857-ba53f7828d9f.png)

Geofencing circle, geofencing object, geofencing noticeification done

**Comment by EdwardYeung6** [comment]
sample:

![Screenshot (190)](https://user-images.githubusercontent.com/57809982/99202699-d34a3200-2764-11eb-812b-55c2fe4f9863.png)
